[package]
name = "mushroomdb-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
description = "CLI binary for mushroomdb: start, shell, and server commands"

[lib]
name = "cli"

[[bin]]
name = "mushroomdb"
path = "src/main.rs"

[features]
default = []
embed-ui = ["server/embed-ui"]

[dependencies]
core-api = { package = "mushroomdb", path = "../core-api", version = "0.1.0" }
server = { package = "mushroomdb-server", path = "../server", version = "0.1.0" }
serde_json = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal", "time"] }
