[package]
name = "mushroomdb-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Low-level storage engine for mushroomdb: WAL, column store, topology, and interner"

[lib]
name = "core_storage"

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
crc32fast = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
crc32fast = { workspace = true }
