#!/usr/bin/env bash
# gen-llms-full.sh — regenerates llms-full.txt at the repo root.
# Run from any directory; the script locates the repo root via git.
# Output: <repo-root>/llms-full.txt
#
# Generator: scripts/gen-llms-full.sh (mushroomdb repo)
# To regenerate: bash scripts/gen-llms-full.sh
# To check it is current without writing: bash scripts/gen-llms-full.sh --check

set -euo pipefail

usage() { echo "usage: gen-llms-full.sh [--check]" >&2; exit 2; }
CHECK=0
case "${1:-}" in
    "") ;;
    --check) CHECK=1 ;;
    *) usage ;;
esac
[[ $# -le 1 ]] || usage

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
OUT="$REPO_ROOT/llms-full.txt"

SITE_DIR="$REPO_ROOT/docs/site"
README="$REPO_ROOT/README.md"

# Ordered list of site docs — index first, then feature docs, then reference
SITE_DOCS=(
    index.md
    quickstart.md
    skill.md
    concurrency.md
    multiprocess.md
    rules.md
    mcp.md
    association-bench.md
    ingest-git.md
    query.md
    api.md
    subscriptions.md
    timetravel.md
    durability.md
    views.md
    fulltext.md
    indexes.md
    algorithms.md
    masks.md
    service.md
    deployment.md
    suggest.md
    testing.md
)

# A page named here that is not on disk used to be skipped without a word, so
# a typo — or a page moved out of docs/site — silently shortened the output.
for doc in "${SITE_DOCS[@]}"; do
    if [[ ! -f "$SITE_DIR/$doc" ]]; then
        echo "gen-llms-full.sh: SITE_DOCS lists $doc, which is not in docs/site" >&2
        exit 1
    fi
done

# Pages deliberately left out, each with its reason. Every other page under
# docs/site has to be in SITE_DOCS: a page in neither list is an error, here
# and under --check, so a new page cannot be missing from the output unseen.
EXCLUDED_DOCS=(
    panic-policy.md   # an internal policy for contributors, not product reference
)

unlisted=0
for path in "$SITE_DIR"/*.md; do
    page="$(basename "$path")"
    found=0
    for doc in "${SITE_DOCS[@]}" "${EXCLUDED_DOCS[@]}"; do
        [[ "$doc" == "$page" ]] && found=1
    done
    if [[ $found -eq 0 ]]; then
        echo "gen-llms-full.sh: docs/site/$page is in neither SITE_DOCS nor EXCLUDED_DOCS" >&2
        unlisted=1
    fi
done
[[ $unlisted -eq 0 ]] || exit 1

# Strip raw HTML tags, keeping every other angle-bracket token intact.
#
# A blanket `s/<[^>]*>//g` cannot be used here: the sources are full of tokens
# that look like tags and are not. CLI placeholders (`<db-dir>`, `<path>`,
# `<dest>`), Rust generics (`Vec<String>`, `Option<f64>`), the GraphML `<data>`
# element, and the map digest's literal `<mixed>` cluster label would all be
# deleted silently, corrupting pasted command lines and real tool output.
#
# So only a known list of HTML tag names is stripped. Three of those names
# collide with real content — `mushroomdb why <db> <a> <b>` writes `<a>` and
# `<b>` bare — so those are stripped only in a form markup actually takes: a
# closing tag, or an opening tag carrying an attribute.
HTML_BLOCK_TAGS='img|br|hr|p|div|details|summary|picture|source|figure|figcaption|h[1-6]'
HTML_AMBIGUOUS_TAGS='a|b|i|em|strong|span|code|sub|sup'

strip_html() {
    sed -E \
        -e "s@</($HTML_BLOCK_TAGS|$HTML_AMBIGUOUS_TAGS)>@@g" \
        -e "s@<($HTML_BLOCK_TAGS|$HTML_AMBIGUOUS_TAGS)[[:space:]][^>]*>@@g" \
        -e "s@<($HTML_BLOCK_TAGS)[[:space:]]*/?>@@g" \
        "$1"
}

generate() {
    echo "# mushroomdb — full LLM reference"
    echo "# Generated by scripts/gen-llms-full.sh (mushroomdb repo)"
    echo "# Source: README.md + every docs/site/*.md page except: ${EXCLUDED_DOCS[*]}"
    echo "# This file is tracked; regenerate and commit with: bash scripts/gen-llms-full.sh"
    echo ""
    echo "---"
    echo ""

    echo "## README"
    echo ""
    # Strip raw HTML tags; keep text, code blocks and literal <angle> tokens
    strip_html "$README"
    echo ""
    echo "---"
    echo ""

    for doc in "${SITE_DOCS[@]}"; do
        echo "## docs/site/$doc"
        echo ""
        # Same rules as the README above
        strip_html "$SITE_DIR/$doc"
        echo ""
        echo "---"
        echo ""
    done
}

if [[ $CHECK -eq 1 ]]; then
    TMP="$(mktemp)"
    trap 'rm -f "$TMP"' EXIT
    generate > "$TMP"
    if ! cmp -s "$TMP" "$OUT"; then
        echo "gen-llms-full.sh: llms-full.txt is not what the generator writes." >&2
        echo "  README.md or a page in docs/site changed without it. Run: bash scripts/gen-llms-full.sh" >&2
        diff "$OUT" "$TMP" | head -20 >&2 || true
        exit 1
    fi
    echo "gen-llms-full.sh: OK — llms-full.txt is current"
    exit 0
fi

generate > "$OUT"

SIZE=$(wc -c < "$OUT")
LINES=$(wc -l < "$OUT")

echo "Generated: $OUT"
echo "  size:  $SIZE bytes"
echo "  lines: $LINES"
