#!/usr/bin/env bash
# gen-llms-full.sh — regenerates llms-full.txt at the repo root.
# Run from any directory; the script locates the repo root via git.
# Output: <repo-root>/llms-full.txt
#
# Generator: scripts/gen-llms-full.sh (mushroomdb repo)
# To regenerate: bash scripts/gen-llms-full.sh

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
OUT="$REPO_ROOT/llms-full.txt"

SITE_DIR="$REPO_ROOT/docs/site"
README="$REPO_ROOT/README.md"

# Ordered list of site docs — index first, then feature docs, then reference
SITE_DOCS=(
    index.md
    quickstart.md
    rules.md
    mcp.md
    query.md
    api.md
    subscriptions.md
    timetravel.md
    views.md
    fulltext.md
    algorithms.md
    suggest.md
    testing.md
)

{
    echo "# mushroomdb — full LLM reference"
    echo "# Generated by scripts/gen-llms-full.sh (mushroomdb repo)"
    echo "# Source: README.md + docs/site/*.md"
    echo "# This file is untracked; regenerate with: bash scripts/gen-llms-full.sh"
    echo ""
    echo "---"
    echo ""

    echo "## README"
    echo ""
    # Strip HTML tags (image tags, raw HTML), keep text and code blocks
    sed 's/<[^>]*>//g' "$README"
    echo ""
    echo "---"
    echo ""

    for doc in "${SITE_DOCS[@]}"; do
        path="$SITE_DIR/$doc"
        if [[ -f "$path" ]]; then
            echo "## docs/site/$doc"
            echo ""
            # Strip HTML tags, keep code blocks and all text
            sed 's/<[^>]*>//g' "$path"
            echo ""
            echo "---"
            echo ""
        fi
    done
} > "$OUT"

SIZE=$(wc -c < "$OUT")
LINES=$(wc -l < "$OUT")

echo "Generated: $OUT"
echo "  size:  $SIZE bytes"
echo "  lines: $LINES"
